# Generated by Django 5.2.17 on 2026-09-17 10:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=accounts.models.utcnow, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
