# Generated by Django 5.2.17 on 2026-09-17 10:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=500, null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='to_be_applied', max_length=50, null=True)),
                ('had_interview', models.BooleanField(default=False, null=True)),
                ('applied_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=accounts.models.utcnow, null=True)),
            ],
            options={
                'db_table': 'job',
            },
        ),
    ]
